2022-02-25 16:06:50 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-25 16:06:50 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration smartir which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-25 16:06:50 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xiaomi_cloud_map_extractor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-25 16:06:50 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-25 16:06:50 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration breaking_changes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-25 16:06:50 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-25 16:06:50 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration esios which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-25 16:06:50 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration clientraw which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-25 16:06:50 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration miio2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-25 16:06:50 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration jsonrest which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-25 16:06:50 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration pvpc_hourly_pricing which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-25 16:06:53 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2022-02-25 16:07:03 WARNING (SyncWorker_6) [miio.device] Found an unsupported model 'viomi.vacuum.v8' for class 'Vacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
2022-02-25 16:07:03 WARNING (MainThread) [homeassistant.helpers.entity] Entity vacuum.robot_aspirador (<class 'custom_components.miio2.vacuum.MiroboVacuum2'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-25 16:07:04 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.3. Please report issue to the custom component author for clientraw using this method at custom_components/clientraw/sensor.py, line 147: with async_timeout.timeout(10, loop=self.hass.loop):
2022-02-25 16:07:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.meteocarlet_station (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-25 16:07:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.meteocarlet_date (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-25 16:07:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.meteocarlet_temperature_degc (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-25 16:07:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.meteocarlet_wind_direction (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-25 16:07:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.meteocarlet_wind_gust_km_h (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-25 16:07:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.meteocarlet_wind_speed_km_h (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-25 16:07:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.meteocarlet_symbol (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-25 16:07:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.meteocarlet_forecast (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-25 16:07:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.meteocarlet_rain_rate (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-25 16:07:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.meteocarlet_daily_rain (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-25 16:07:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.meteocarlet_pressure (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-25 16:07:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.meteocarlet_humidity (<class 'custom_components.clientraw.sensor.ClientrawSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-25 16:07:04 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that uses str for device registry entry_type. This is deprecated and will stop working in Home Assistant 2022.3, it should be updated to use DeviceEntryType instead. Please report this issue.
Stack (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 203, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 191, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 119, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 501, in _async_add_entity
    device = device_registry.async_get_or_create(**processed_dev_info)  # type: ignore[arg-type]
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 367, in async_get_or_create
    report(  # type: ignore[unreachable]
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 74, in report
    _LOGGER.warning(msg, stack_info=True)
Stack (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 203, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 191, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 119, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 501, in _async_add_entity
    device = device_registry.async_get_or_create(**processed_dev_info)  # type: ignore[arg-type]
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 367, in async_get_or_create
    report(  # type: ignore[unreachable]
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 74, in report
    _LOGGER.warning(msg, stack_info=True)
2022-02-25 16:07:04 WARNING (MainThread) [custom_components.esios.sensor] Setup of ESIOS PVPC (sensor.esios_pvpc) finished
2022-02-25 16:07:04 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that uses str for device registry entry_type. This is deprecated and will stop working in Home Assistant 2022.3, it should be updated to use DeviceEntryType instead. Please report this issue.
Stack (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 203, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 191, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 119, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 501, in _async_add_entity
    device = device_registry.async_get_or_create(**processed_dev_info)  # type: ignore[arg-type]
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 367, in async_get_or_create
    report(  # type: ignore[unreachable]
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 74, in report
    _LOGGER.warning(msg, stack_info=True)
Stack (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 203, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 191, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 119, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 501, in _async_add_entity
    device = device_registry.async_get_or_create(**processed_dev_info)  # type: ignore[arg-type]
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 367, in async_get_or_create
    report(  # type: ignore[unreachable]
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 74, in report
    _LOGGER.warning(msg, stack_info=True)
2022-02-25 16:07:04 WARNING (MainThread) [custom_components.esios.sensor] Setup of ESIOS CO2 intensity (sensor.esios_co2_intensity) finished
2022-02-25 16:07:04 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that uses str for device registry entry_type. This is deprecated and will stop working in Home Assistant 2022.3, it should be updated to use DeviceEntryType instead. Please report this issue.
Stack (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 203, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 191, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 119, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 501, in _async_add_entity
    device = device_registry.async_get_or_create(**processed_dev_info)  # type: ignore[arg-type]
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 367, in async_get_or_create
    report(  # type: ignore[unreachable]
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 74, in report
    _LOGGER.warning(msg, stack_info=True)
Stack (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 203, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 191, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 119, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 501, in _async_add_entity
    device = device_registry.async_get_or_create(**processed_dev_info)  # type: ignore[arg-type]
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 367, in async_get_or_create
    report(  # type: ignore[unreachable]
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 74, in report
    _LOGGER.warning(msg, stack_info=True)
2022-02-25 16:07:04 WARNING (MainThread) [custom_components.esios.sensor] Setup of ESIOS Grid CO2 free percentage (sensor.esios_grid_co2_free_percentage) finished
2022-02-25 16:07:05 WARNING (MainThread) [homeassistant.components.energy.sensor] Found unexpected state_class None for sensor.shelly_energy
2022-02-25 16:07:05 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for espcam1 @ espcam1.casa: Error resolving IP address: [Errno -2] Name does not resolve
2022-02-25 16:07:05 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'temp_sensor_temp' when rendering '{{ value_json.temp_sensor_temp }}'
2022-02-25 16:07:05 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'temp_sensor_humidity' when rendering '{{ value_json.temp_sensor_humidity }}'
2022-02-25 16:07:14 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Mop Pro' for xiaomi_miio integration not ready yet; Retrying in background
2022-02-25 16:07:24 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: timed out
2022-02-25 16:07:27 WARNING (MainThread) [homeassistant.config_entries] Config entry 'HL-L2340D E73870F7N787320' for brother integration not ready yet: No SNMP response received before timeout; Retrying in background
2022-02-25 16:07:35 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'temp_sensor_temp' when rendering '{{ value_json.temp_sensor_temp }}'
2022-02-25 16:07:35 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'temp_sensor_humidity' when rendering '{{ value_json.temp_sensor_humidity }}'
2022-02-25 16:07:44 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: timed out
2022-02-25 16:07:47 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: timed out
2022-02-25 16:08:05 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'temp_sensor_temp' when rendering '{{ value_json.temp_sensor_temp }}'
2022-02-25 16:08:05 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'temp_sensor_humidity' when rendering '{{ value_json.temp_sensor_humidity }}'
2022-02-25 16:08:07 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: timed out
2022-02-25 16:08:08 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: timed out
2022-02-25 16:08:27 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: timed out
2022-02-25 16:08:35 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'temp_sensor_temp' when rendering '{{ value_json.temp_sensor_temp }}'
2022-02-25 16:08:35 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'temp_sensor_humidity' when rendering '{{ value_json.temp_sensor_humidity }}'
2022-02-25 16:08:37 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: timed out
2022-02-25 16:08:58 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: timed out
2022-02-25 16:09:05 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'temp_sensor_temp' when rendering '{{ value_json.temp_sensor_temp }}'
2022-02-25 16:09:05 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'temp_sensor_humidity' when rendering '{{ value_json.temp_sensor_humidity }}'
2022-02-25 16:09:09 WARNING (Thread-99) [homeassistant.util.executor] Thread[SyncWorker_7] is still running at shutdown: File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/__init__.py", line 232, in update
    timer = device.timer()
  File "/usr/local/lib/python3.9/site-packages/miio/click_common.py", line 186, in _wrap
    self._fetch_info()
  File "/usr/local/lib/python3.9/site-packages/miio/integrations/vacuum/roborock/vacuum.py", line 213, in _fetch_info
    info = super()._fetch_info()
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 149, in _fetch_info
    devinfo = DeviceInfo(self.send("miIO.info"))
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 103, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
2022-02-25 16:09:10 WARNING (Thread-99) [homeassistant.util.executor] Thread[SyncWorker_7] is still running at shutdown: File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/__init__.py", line 232, in update
    timer = device.timer()
  File "/usr/local/lib/python3.9/site-packages/miio/click_common.py", line 186, in _wrap
    self._fetch_info()
  File "/usr/local/lib/python3.9/site-packages/miio/integrations/vacuum/roborock/vacuum.py", line 213, in _fetch_info
    info = super()._fetch_info()
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 149, in _fetch_info
    devinfo = DeviceInfo(self.send("miIO.info"))
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 103, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
