2021-12-05 09:38:54 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartir which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-05 09:38:54 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-05 09:38:54 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xiaomi_cloud_map_extractor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-05 09:38:54 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration esios which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-05 09:38:54 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration miio2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-05 09:38:54 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration clientraw which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-05 09:38:54 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-05 09:38:54 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration jsonrest which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-05 09:38:54 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration breaking_changes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-05 09:38:54 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration pvpc_hourly_pricing which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-05 09:39:08 WARNING (MainThread) [homeassistant.components.octoprint] The 'octoprint' option near /config/configuration.yaml:0 is deprecated, please remove it from your configuration
2021-12-05 09:39:09 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2021-12-05 09:39:09 WARNING (MainThread) [homeassistant.components.nmap_tracker.device_tracker] Your Nmap Tracker configuration has been imported into the UI, please remove it from configuration.yaml. 
2021-12-05 09:39:09 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy nmap_tracker
2021-12-05 09:39:09 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry kk@martinezpenya.es for tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/tuya/__init__.py", line 63, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
  File "/usr/src/homeassistant/homeassistant/components/tuya/__init__.py", line 75, in _init_tuya_sdk
    auth_type = AuthType(entry.data[CONF_AUTH_TYPE])
KeyError: 'auth_type'
2021-12-05 09:39:09 WARNING (MainThread) [alexapy.alexalogin] No access token found; falling back to credential login instead of oauth.
2021-12-05 09:39:10 WARNING (MainThread) [alexapy.alexalogin] No access token found; falling back to credential login instead of oauth.
2021-12-05 09:39:10 WARNING (MainThread) [custom_components.esios.sensor] Setup of ESIOS PVPC (sensor.esios_pvpc) finished
2021-12-05 09:39:10 WARNING (MainThread) [custom_components.esios.sensor] Setup of ESIOS CO2 intensity (sensor.esios_co2_intensity) finished
2021-12-05 09:39:10 WARNING (MainThread) [custom_components.esios.sensor] Setup of ESIOS Grid CO2 free percentage (sensor.esios_grid_co2_free_percentage) finished
2021-12-05 09:39:10 WARNING (MainThread) [homeassistant.components.broadlink.switch] The switch platform is deprecated, except for custom IR/RF switches. Please refer to the Broadlink documentation to catch up
2021-12-05 09:39:10 WARNING (MainThread) [homeassistant.components.broadlink.switch] The switch platform is deprecated, except for custom IR/RF switches. Please refer to the Broadlink documentation to catch up
2021-12-05 09:39:10 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform utility_meter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 714, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/utility_meter/sensor.py", line 305, in async_added_to_hass
    float(state.attributes.get(ATTR_LAST_PERIOD))
ValueError: could not convert string to float: 'None'
2021-12-05 09:39:10 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform utility_meter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 714, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/utility_meter/sensor.py", line 305, in async_added_to_hass
    float(state.attributes.get(ATTR_LAST_PERIOD))
ValueError: could not convert string to float: 'None'
2021-12-05 09:39:10 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up utility_meter platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 714, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/utility_meter/sensor.py", line 305, in async_added_to_hass
    float(state.attributes.get(ATTR_LAST_PERIOD))
ValueError: could not convert string to float: 'None'
2021-12-05 09:39:10 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json is not none and value_json.state == "running" }}'
2021-12-05 09:39:10 ERROR (MainThread) [homeassistant.components.rest.switch] Got non-ok response from resource: 404
2021-12-05 09:39:10 ERROR (MainThread) [custom_components.smartir.climate] Unable to update from temperature sensor: could not convert string to float: 'unavailable'
2021-12-05 09:39:10 ERROR (MainThread) [custom_components.smartir.climate] Unable to update from humidity sensor: could not convert string to float: 'unavailable'
2021-12-05 09:39:10 ERROR (MainThread) [custom_components.smartir.climate] Unable to update from temperature sensor: could not convert string to float: 'unavailable'
2021-12-05 09:39:10 ERROR (MainThread) [custom_components.smartir.climate] Unable to update from humidity sensor: could not convert string to float: 'unavailable'
2021-12-05 09:39:11 WARNING (MainThread) [alexapy.alexawebsocket] mac_dms not detected; websocket likely won't connect
2021-12-05 09:39:11 WARNING (MainThread) [alexapy.alexawebsocket] mac_dms not detected; websocket likely won't connect
2021-12-05 09:39:12 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'temp_sensor_temp' when rendering '{{ value_json.temp_sensor_temp }}'
2021-12-05 09:39:12 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'temp_sensor_humidity' when rendering '{{ value_json.temp_sensor_humidity }}'
2021-12-05 09:39:12 ERROR (MainThread) [homeassistant.components.octoprint] Unable to retrieve printer information: Printer offline
2021-12-05 09:39:12 ERROR (MainThread) [homeassistant.components.octoprint.sensor] Printer appears to be offline, skipping temperature sensors
2021-12-05 09:39:13 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry david@martinezpenya.es - amazon.es for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 363, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 164, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2021-12-05 09:39:18 WARNING (MainThread) [homeassistant.components.vacuum] Setup of vacuum platform miio2 is taking over 10 seconds.
2021-12-05 09:39:19 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Mop Pro' for xiaomi_miio integration not ready yet; Retrying in background
2021-12-05 09:39:29 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: timed out
2021-12-05 09:39:29 WARNING (SyncWorker_7) [custom_components.miio2.vacuum] Got exception while fetching the state: No response from the device
2021-12-05 09:39:29 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: timed out
2021-12-05 09:39:32 WARNING (MainThread) [homeassistant.config_entries] Config entry 'HL-L2340D E73870F7N787320' for brother integration not ready yet: No SNMP response received before timeout; Retrying in background
2021-12-05 09:39:42 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'temp_sensor_humidity' when rendering '{{ value_json.temp_sensor_humidity }}'
2021-12-05 09:39:42 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'temp_sensor_temp' when rendering '{{ value_json.temp_sensor_temp }}'
2021-12-05 09:39:50 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: timed out
2021-12-05 09:39:53 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: timed out
2021-12-05 09:39:59 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.robot_aspirador is taking over 10 seconds
2021-12-05 09:40:08 WARNING (MainThread) [homeassistant.components.octoprint] The 'octoprint' option is deprecated, please remove it from your configuration
2021-12-05 09:40:09 WARNING (MainThread) [homeassistant.components.vacuum] Updating miio2 vacuum took longer than the scheduled update interval 0:00:20
2021-12-05 09:40:09 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: timed out
2021-12-05 09:40:09 WARNING (SyncWorker_7) [custom_components.miio2.vacuum] Got exception while fetching the state: No response from the device
2021-12-05 09:40:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bw1_hourly_energy (KW) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None
2021-12-05 09:40:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bw2_hourly_energy (KW) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None
2021-12-05 09:40:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bw2_daily_energy (KW) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None
2021-12-05 09:40:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bw3_hourly_energy (KW) does not match the unit of already compiled statistics (W). Generation of long term statistics will be suppressed unless the unit changes back to W
2021-12-05 09:40:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bw3_daily_energy (KW) does not match the unit of already compiled statistics (W). Generation of long term statistics will be suppressed unless the unit changes back to W
2021-12-05 09:40:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bw3_monthly_energy (KW) does not match the unit of already compiled statistics (W). Generation of long term statistics will be suppressed unless the unit changes back to W
2021-12-05 09:40:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bw6_hourly_energy (KW) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None
2021-12-05 09:40:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bw7_hourly_energy (KW) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None
2021-12-05 09:40:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bw7_daily_energy (KW) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None
2021-12-05 09:40:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bw8_hourly_energy (KW) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None
2021-12-05 09:40:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bw8_daily_energy (KW) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None
2021-12-05 09:40:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bw9_hourly_energy (KW) does not match the unit of already compiled statistics (W). Generation of long term statistics will be suppressed unless the unit changes back to W
2021-12-05 09:40:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bw9_daily_energy (KW) does not match the unit of already compiled statistics (W). Generation of long term statistics will be suppressed unless the unit changes back to W
2021-12-05 09:40:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.bw9_monthly_energy (KW) does not match the unit of already compiled statistics (W). Generation of long term statistics will be suppressed unless the unit changes back to W
2021-12-05 09:40:12 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'temp_sensor_humidity' when rendering '{{ value_json.temp_sensor_humidity }}'
2021-12-05 09:40:12 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'temp_sensor_temp' when rendering '{{ value_json.temp_sensor_temp }}'
2021-12-05 09:40:12 WARNING (MainThread) [homeassistant.components.octoprint] The 'octoprint' option is deprecated, please remove it from your configuration
2021-12-05 09:40:13 ERROR (MainThread) [custom_components.smartir.climate] Unable to update from temperature sensor: could not convert string to float: 'unavailable'
2021-12-05 09:40:13 ERROR (MainThread) [custom_components.smartir.climate] Unable to update from humidity sensor: could not convert string to float: 'unavailable'
2021-12-05 09:40:13 ERROR (MainThread) [custom_components.smartir.climate] Unable to update from temperature sensor: could not convert string to float: 'unavailable'
2021-12-05 09:40:13 ERROR (MainThread) [custom_components.smartir.climate] Unable to update from humidity sensor: could not convert string to float: 'unavailable'
2021-12-05 09:40:13 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: timed out
2021-12-05 09:40:13 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: timed out
2021-12-05 09:40:14 WARNING (Thread-101) [homeassistant.util.executor] Thread[SyncWorker_9] is still running at shutdown: File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/__init__.py", line 228, in update
    fan_speeds = device.fan_speed_presets()
  File "/usr/local/lib/python3.9/site-packages/miio/vacuum.py", line 573, in fan_speed_presets
    self._autodetect_model()
  File "/usr/local/lib/python3.9/site-packages/miio/vacuum.py", line 536, in _autodetect_model
    info = self.info()
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 133, in info
    return DeviceInfo(self.send("miIO.info"))
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 97, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
2021-12-05 09:40:15 WARNING (Thread-101) [homeassistant.util.executor] Thread[SyncWorker_9] is still running at shutdown: File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/__init__.py", line 228, in update
    fan_speeds = device.fan_speed_presets()
  File "/usr/local/lib/python3.9/site-packages/miio/vacuum.py", line 573, in fan_speed_presets
    self._autodetect_model()
  File "/usr/local/lib/python3.9/site-packages/miio/vacuum.py", line 536, in _autodetect_model
    info = self.info()
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 133, in info
    return DeviceInfo(self.send("miIO.info"))
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 97, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
